alter table COVIDCHECKUP_DIAGNOSIS add constraint FK_COVIDCHECKUP_DIAGNOSIS_ON_DOCTOR foreign key (DOCTOR_ID) references COVIDCHECKUP_DOCTOR(ID);
create index IDX_COVIDCHECKUP_DIAGNOSIS_ON_DOCTOR on COVIDCHECKUP_DIAGNOSIS (DOCTOR_ID);
